changelog:
  categories:
    - title: "💥 Breaking Changes"
      labels:
        - breaking-change
    - title: "✨ New Features"
      labels:
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
    - title: "📦 Dependency Updates"
      labels:
        - dependencies
        - github-actions
    - title: "🔧 Other Changes"
      labels:
        - "*"
