name: CI - Maven Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup JDK 25
        uses: actions/setup-java@v6
        with:
          java-version: 25
          distribution: temurin
          cache: maven

      - name: Run maven clean package
        run: mvn -B clean package
